### ISSUE TITLE
Cannot be installed under luarocks/lua 5.4

### ISSUE THREAD

**Issue by oktoberfest6** [Tieske/timerwheel.lua#1]
Hi,

timerwheel does not install under luarocks for lua 5.4.
the culprit appears to be the line `"lua >= 5.1, < 5.4"` in the file timerwheel-scm-1.rockspec.
Changing the '5.4' to '5.5' allows building/installation of timerwheel under lua 5.4/luarocks.

**Comment by Tieske** [comment]
thx for the nudge, should be fixed now

**Comment by oktoberfest6** [comment]
Works well under linux/windows.  Thank you !
